spring:
  jackson:
    default-property-inclusion: NON_NULL

server:
  shutdown: GRACEFUL
  error:
    include-stacktrace: NEVER

logging:
  level:
    com.chak.sc: DEBUG

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure.include: '*'

database:
  password: '{cipher}AQBTn8Re4npnO0mcoOAkv2/yjiIGucE18WsOPdB2vbiPtzNdISmvFbydDFk9DIyxi0tW+bVRts6Qefr8/eT3AFWfKfnCTpwWvjV7XJCV1tEeQ+gRdKPj+4HULc8Pczp6Ig8eqhq8BB9k1WvOAcQ199NkZ1tsG0kuwJIm+i6T2ugfzC0uepzn/1fEBbSGITvt8rY8Y6W5Uku2f1SPhW5G1MTS7Z8kG7dz2UQSyJoJveFzmXbWroJ2dj16LsUsXW+0hZOgjlnL+f/EdyiqgNQl8Eu9L//4xsjiPP3+Enq8mgDstDnasnHPHpCJInNsWYx7goHDXpk5iYquHExVIKZB9WnsXnp/s9fL6rRE+U4WtfhLN4aS8dReSd9OjyQ2OSpure0='
  username: postgres
  host: 192.168.0.151
  port: 5432
  name: postgres

discovery:
  host: localhost
  port: 8080

gateway:
  host: localhost
  port: 9292
