server:
  port: 0
  error:
    include-stacktrace: NEVER

database:
  password: '{cipher}AQAFIfJ5D+388OmC4X81slkbctq4LLRNlOt0Wasd2M/M3K2h61MDZvYzkSU0qMosistqxJvkxkn4tVfFnRkQqoy8XgALhjL5z+EFWWTfZa1RD//oSDFWHWhQUReZYtMup1DOKFvGVB5qaqAWHuCG59Msl8Z/mlTaiDhdS835NlOi+v8TQ38Gba7PtN6uDiDNxctuquhc548gvx7SKdd/f4hv+5YUC9Hj9at2noSRqZzChziwrcvX9psOhQu/raiUU7A2cDMLQEtFuO2dBKxgrANN8zFltmDIbJnNtNpJmkX6UQ3ajB6CX8CVLz4Sl425hrtPOG3v0p07/ncDyja7M2HzpyNURxaUuSpLzA0gfDl4w6hYnsLQuD+uXh5HwJTKf9RxCQGhSBEcUDBhpo9BsjAp34rGo/dI1HzS22yqxywsnw=='

spring:
  r2dbc:
    url: r2dbc:pool:postgres://kmvckmre:${database.password}@satao.db.elephantsql.com:5432/kmvckmre
    name: kmvckmre
    username: kmvckmre
    password: ${database.password}
  data:
    r2dbc:
      repositories:
        enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.value}
    prefer-ip-address: true
  client:
    serviceUrl.defaultZone: http://localhost:8080/eureka
    region: default