server:
  port: 9292

management:
  endpoints:
    web:
      exposure.include: "*"

spring:
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

gateway:
  retry-count: 5

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8080/eureka
    region: default